## 0.Install Dependencies and Bring in Data

In [1]:
!pip install tensorflow tensorflow-gpu pandas matplotlib scikit-learn

In [2]:
import os
import pandas as pd  
import tensorflow as tf 
import numpy as np

In [8]:
 os.path.join( 'jigsaw-toxic-comment-classification-challeng','train.csv')

'jigsaw-toxic-comment-classification-challeng\\train.csv'

In [18]:
df = pd.read_csv(os.path.join('jigsaw-toxic-comment-classification-challenge','train.csv', 'train.csv'))

In [16]:
df = pd.read_csv(r'D:\toxic\jigsaw-toxic-comment-classification-challenge\train.csv\train.csv')

In [32]:
df[df['toxic']==1].head()

id                                       comment_text  \
6   0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
12  0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......   
16  0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...   
42  001810bf8c45bf5f  You are gay or antisemmitian? \n\nArchangel WH...   
43  00190820581d90ce           FUCK YOUR FILTHY MOTHER IN THE ASS, DRY!   

    toxic  severe_toxic  obscene  threat  insult  identity_hate  
6       1             1        1       0       1              0  
12      1             0        0       0       0              0  
16      1             0        0       0       0              0  
42      1             0        1       0       1              1  
43      1             0        1       0       1              0

In [30]:
df.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [26]:
df.iloc[3]['comment_text']

'"\nMore\nI can\'t make any real suggestions on improvement - I wondered if the section statistics should be later on, or a subsection of ""types of accidents""  -I think the references may need tidying so that they are all in the exact same format ie date format etc. I can do that later on, if no-one else does first - if you have any preferences for formatting style on references or want to do it yourself please let me know.\n\nThere appears to be a backlog on articles for review so I guess there may be a delay until a reviewer turns up. It\'s listed in the relevant form eg Wikipedia:Good_article_nominations#Transport  "'

In [28]:
df[df. columns[2:]].iloc[3]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 3, dtype: int64

## 1.Preprocess

In [20]:
!pip list

Package                      Version
---------------------------- --------------
absl-py                      2.1.0
aiohappyeyeballs             2.4.3
aiohttp                      3.10.10
aiosignal                    1.3.1
aiosqlite                    0.20.0
albucore                     0.0.19
albumentations               1.4.19
annotated-types              0.7.0
anyio                        4.6.0
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
arrow                        1.3.0
asttokens                    2.4.1
astunparse                   1.6.3
async-lru                    2.0.4
async-timeout                4.0.3
attrs                        24.2.0
babel                        2.16.0
beautifulsoup4               4.12.3
bleach                       6.1.0
cachetools                   5.5.0
certifi                      2024.8.30
cffi                         1.17.1
charset-normalizer           3.4.0
click                        8.1.7
cloudpickle                  

In [21]:
from tensorflow.keras.layers import TextVectorization

In [55]:
X = df [ 'comment_text']
y= df [df.columns[2:]].values

In [43]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [44]:
df[df.columns[2:]]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [41]:
df['comment_text']

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [49]:
 MAX_FEATURES = 200000

In [52]:
vectorizer = TextVectorization(max_tokens = MAX_FEATURES, output_sequence_length =1800, output_mode = 'int')

In [56]:
type(X)

pandas.core.series.Series

In [59]:
 vectorizer.adapt(X.values)

In [ ]:
vectorizer.get_vocabulary()

In [61]:
vectorized_text = vectorizer(X.values)

In [62]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  643,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2506, ...,     0,     0,     0],
       [  425,   440,    70, ...,     0,     0,     0],
       ...,
       [32141,  7329,   383, ...,     0,     0,     0],
       [    5,    12,   533, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [65]:
tf.data.Dataset.list_files

<function tensorflow.python.data.ops.dataset_ops.DatasetV2.list_files(file_pattern, shuffle=None, seed=None, name=None)>

In [69]:
#MCSHBAP -map,cache,shuffle,batsh,prefetch from_tensor_slices, list_dir, list_file
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)

In [71]:
batch_X,batch_y = dataset.as_numpy_iterator().next()

In [72]:
batch_y.shape

(16, 6)

In [73]:
len(dataset)*.7

6981.799999999999

In [77]:
train = dataset.take(int(len(dataset)*.7))
val= dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [80]:
train_generator = train.as_numpy_iterator()

In [87]:
train_generator.next()

(array([[  574,    40,    25, ...,     0,     0,     0],
        [ 3813,  6978, 57544, ...,     0,     0,     0],
        [  754,    76,    55, ...,     0,     0,     0],
        ...,
        [ 1351,   237,   217, ...,     0,     0,     0],
        [   30,   260,    43, ...,     0,     0,     0],
        [  912,  1504,  5316, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

## 2. Creat Sequential Model

In [101]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dropout,Bidirectional,Dense

In [109]:
model = Sequential()
model.add(Embedding( MAX_FEATURES+1,32))
model.add (Bidirectional(LSTM(32,activation = 'tanh')))
model.add(Dense(128,activation = 'relu'))
model.add(Dense(256, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(6 , activation = 'sigmoid'))

In [110]:
 model.compile(loss = 'BinaryCrossentropy', optimizer = 'Adam')

In [111]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, None, 32)          6400032   
                                                                 
 bidirectional_2 (Bidirectio  (None, 64)               16640     
 nal)                                                            
                                                                 
 dense_8 (Dense)             (None, 128)               8320      
                                                                 
 dense_9 (Dense)             (None, 256)               33024     
                                                                 
 dense_10 (Dense)            (None, 128)               32896     
                                                                 
 dense_11 (Dense)            (None, 6)                 774       
                                                      

In [ ]:
history = model.fit(train,epochs=1, validation_data=val)

In [ ]:
from matplotlib import pyplot as plt

In [1]:
plt.figure(figsize=(8, 5))
pd.DataFrame(history.history).plot()
plt.show()

NameError: name 'plt' is not defined

## 3. Make Prediction 

In [ ]:
input_text = vectorizer('Your input text here') 

In [ ]:
batch = test.as_numpy_iterator().next()

In [ ]:
batch_X,batch_y = test.as_numpy_iterator().next()

In [ ]:
batch_y

In [ ]:
(model.predict(batch_X)>0.5).astype(int)

In [ ]:
impot_text = vetorizer ('You freaking suck!')

In [ ]:
model.predict(np.expand_dims(input_text,0))

In [ ]:
res = model.predict(np.expand_dims(input_text,0))

## 4.Evaluate Model

In [ ]:
from tensorflow.keras.metrics import Precision , Recall , CategoricalAccuracy

In [ ]:
pre = Precision()
re = Recal()
acc = CategoricalAccuracy()

In [ ]:
for batch in test.as_numpy_iterator():
    X_true,y_true = batch
    yhat = model.predict(X_true)
    y_true = y_true.flatten()
    yhat = yhat.flatten()
    pre.update_state(y_true,yhat)
    re.update_state(y_true,yhat)
    acc.update_state(y_true, yhat)

from (f'Precision: {pre.result().numpy()},
        Recall:{re.result().numpy},
        Accuracy:{acc.result.numpy()}')

  # 5.Test and Gradio

In [ ]:
!pip install gradion jinja2

In [ ]:
import gradio as gr
import tensorflow as tf

In [ ]:
model.save ('toxiccity.h5')

In [ ]:
model = tf.keras.models.load_model('toxiccity.h5')

In [ ]:
input_str = vectorizer('hey i freaken hate you ! I am coming for you. I\'m going to hurt you')

In [ ]:
res = model.predict(np.expand_dims(input_str.0)) 

In [ ]:
df.columns[2:]

In [ ]:
res

In [ ]:
def score_comment(comment):
    vectorized_comment = vectorizer ([comment])
    results = model.predict(vectorized_comment)


    text = ''
    for idx, col in enumerate (df.columns[2:-1]):
        text+= '{} :{}\n'.format(col,results[0][idx]>0.5)
    return text 

In [ ]:
interface = gr.Interface(fn = score_comment ,
                         inputs= gr.inputs.Textbox(lines=2,placeholder = ' Comment to score')
                         outputs = 'text')

In [ ]:
interface.launch(share = True)